version: "3.9"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      image: compose-back-optimal-image
    env_file:
    - ./.env
    restart: on-failure
    ports:
      - '4000:3000'
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: compose-front-optimal-image
    ports:
      - '3005:80'

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - postgres_data:/data/postgres
    env_file: ./.env

  adminer:
      container_name: adminer
      image: adminer
      ports:
      - 8081:8080

volumes:
  postgres_data:
