version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: compose-back-optimal-image
    networks:
      - frontend
      - backend
    env_file:
    - .env
    restart: on-failure
    ports:
      - '4000:3000'
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    networks:
      - frontend
    image: compose-front-optimal-image
    ports:
      - '3005:80'

  postgres:
    container_name: postgres
    image: postgres
    networks:
      - backend
    volumes:
      - ./postgres_data:/data/postgres
    env_file:
    - .env

  adminer:
    networks:
    - backend
    container_name: adminer
    image: adminer
    ports:
    - 8081:8080

networks:
  backend: 
    driver: bridge
    internal: true
  frontend:
    driver: bridge

volumes:
  postgres_data:
