version: "3.9"
services:
  backend:
    container_name: 'backend'
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    restart: on-failure
    ports:
      - '4000:3000'
    depends_on:
      - postgres

  frontend:
    container_name: 'frontend'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8081:80'

  postgres:
    container_name: 'postgres'
    image: postgres:12-alpine
    restart: always
    env_file: ./backend/.env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local